name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        include:
          - path: front/Canvas/exec/dynamicPointAndLine
            name: dynamic-point-and-line
         
    steps:
      - uses: actions/checkout@v4

  
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{matrix.path}}/dist --project-name=${{ matrix.name }}

          