name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        include:
          - path: front/Canvas/exec/dynamicPointAndLine
            name: dynamic-point-and-line
          - path: front/Canvas/exec/simpleCanvasGraph
            name: simple-canvas-graph
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ matrix.path }}

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.path }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID  }}

